from typing import Protocol
from app.core.models import Entry, Value


class StoragePort(Protocol):
    def get(self, key: str) -> Entry: ...
    def set(self, key: str, value: Value, value_type: str, ttl: int | None) -> None: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
    def update_value(self, key: str, value: Value) -> None: ...
    def expire(self, key: str, ttl: int) -> None: ...
    def keys(self) -> list[str]: ...
    def flush(self) -> None: ...
